### ISSUE TITLE
Add support for Python files

### ISSUE THREAD

**Issue by charlax** [cyphactor/vim-open-alternate#2]
Hey - would you be interesting in adding support for Python files?

If you are, I'll be submitting a PR.

Thanks,

Chx

**Comment by cyphactor** [comment]
Sure. I think we should probably figure out a way of grouping the handlers in code though. Just to keep things organized. The other thing we will need to figure out is if they clash with existing rules. If so then we will have to look at swapping rules in and out depending on filetype.

**Comment by cyphactor** [comment]
Also. There must be test coverage

**Comment by cyphactor** [comment]
@charlax I added full test coverage so it is much easier to determine if there are clashes between rules. Someone just made a PR for Elixir. If you are interested in contributing still, it might be a decent template for you (https://github.com/cyphactor/vim-open-alternate/pull/4).

**Comment by cyphactor** [comment]
I am closing this issue because this functionality now exists in my replacement project for this project, https://github.com/cyphactor/alt.
