### ISSUE TITLE
Hanami framework support

### ISSUE THREAD

**Issue by RyanHedges** [cyphactor/vim-open-alternate#6]
- [x] Container architecture applications with controllers and views
```
apps/web/controllers/users/create.rb <=> spec/web/controllers/users/create_spec.rb
```
- [x] Lib directory using project name
```
lib/bookshelf/entities/user.rb <=> spec/bookshelf/entities/user_spec.rb
```
- [ ] container application business logic libs
```
apps/web/people_mover.rb <=> spec/web/people_mover_spec.rb
```
- [ ] switching using features for cucumber

**Comment by cyphactor** [comment]
@RyanHedges looks like the `lib` directory support here is exactly the same as the `lib` support described in #7.

**Comment by cyphactor** [comment]
The following would have to be done in addition to support the Hanami app architecture

- [ ] App architecture applications with controllers and views
```text
app/controllers/users/create.rb <=> spec/controllers/users/create_spec.rb
```

**Comment by cyphactor** [comment]
Functionality for this now exists in the replacement project for this, https://github.com/cyphactor/alt.

Therefore, I am closing this issue.
